from discord import Locale
from discord import app_commands


TRANSLATIONS = {

    # ========================================
    # 분석
    # ========================================

    "분석": {
        Locale.american_english: "analysis",
        Locale.british_english: "analysis",
        Locale.bulgarian: "анализ",
        Locale.chinese: "分析",
        Locale.taiwan_chinese: "分析",
        Locale.croatian: "analiza",
        Locale.czech: "analýza",
        Locale.indonesian: "analisis",
        Locale.danish: "analyse",
        Locale.dutch: "analyse",
        Locale.finnish: "analyysi",
        Locale.french: "analyse",
        Locale.german: "analyse",
        Locale.greek: "ανάλυση",
        Locale.hindi: "विश्लेषण",
        Locale.hungarian: "elemzés",
        Locale.italian: "analisi",
        Locale.japanese: "分析",
        Locale.korean: "분석",
        Locale.latin_american_spanish: "analisis",
        Locale.lithuanian: "analizė",
        Locale.norwegian: "analyse",
        Locale.polish: "analiza",
        Locale.brazil_portuguese: "análise",
        Locale.romanian: "analiză",
        Locale.russian: "анализ",
        Locale.spain_spanish: "análisis",
        Locale.swedish: "analys",
        Locale.thai: "วิเคราะห์",
        Locale.turkish: "analiz",
        Locale.ukrainian: "аналіз",
        Locale.vietnamese: "phân-tích",
    },

    "오늘": {
        Locale.american_english: "today",
        Locale.british_english: "today",
        Locale.bulgarian: "днес",
        Locale.chinese: "今天",
        Locale.taiwan_chinese: "今天",
        Locale.croatian: "danas",
        Locale.czech: "dnes",
        Locale.indonesian: "hari-ini",
        Locale.danish: "i-dag",
        Locale.dutch: "vandaag",
        Locale.finnish: "tänään",
        Locale.french: "aujourd-hui",
        Locale.german: "heute",
        Locale.greek: "σήμερα",
        Locale.hindi: "आज",
        Locale.hungarian: "ma",
        Locale.italian: "oggi",
        Locale.japanese: "今日",
        Locale.korean: "오늘",
        Locale.latin_american_spanish: "hoy",
        Locale.lithuanian: "šiandien",
        Locale.norwegian: "i-dag",
        Locale.polish: "dzisiaj",
        Locale.brazil_portuguese: "hoje",
        Locale.romanian: "astăzi",
        Locale.russian: "сегодня",
        Locale.spain_spanish: "hoy",
        Locale.swedish: "idag",
        Locale.thai: "วันนี้",
        Locale.turkish: "bugün",
        Locale.ukrainian: "сьогодні",
        Locale.vietnamese: "hôm-nay",
    },

    "이번주": {
        Locale.american_english: "this-week",
        Locale.british_english: "this-week",
        Locale.bulgarian: "тази-седмица",
        Locale.chinese: "本周",
        Locale.taiwan_chinese: "本週",
        Locale.croatian: "ovaj-tjedan",
        Locale.czech: "tento-týden",
        Locale.indonesian: "minggu-ini",
        Locale.danish: "denne-uge",
        Locale.dutch: "deze-week",
        Locale.finnish: "tämä-viikko",
        Locale.french: "cette-semaine",
        Locale.german: "diese-woche",
        Locale.greek: "αυτή-την-εβδομάδα",
        Locale.hindi: "इस-सप्ताह",
        Locale.hungarian: "ezen-a-heten",
        Locale.italian: "questa-settimana",
        Locale.japanese: "今週",
        Locale.korean: "이번주",
        Locale.latin_american_spanish: "esta-semana",
        Locale.lithuanian: "ši-savaitė",
        Locale.norwegian: "denne-uken",
        Locale.polish: "ten-tydzień",
        Locale.brazil_portuguese: "esta-semana",
        Locale.romanian: "săptămâna-aceasta",
        Locale.russian: "эта-неделя",
        Locale.spain_spanish: "esta-semana",
        Locale.swedish: "denna-vecka",
        Locale.thai: "สัปดาห์นี้",
        Locale.turkish: "bu-hafta",
        Locale.ukrainian: "цього-тижня",
        Locale.vietnamese: "tuần-này",
    },

    "이번달": {
        Locale.american_english: "this-month",
        Locale.british_english: "this-month",
        Locale.bulgarian: "този-месец",
        Locale.chinese: "本月",
        Locale.taiwan_chinese: "本月",
        Locale.croatian: "ovaj-mjesec",
        Locale.czech: "tento-měsíc",
        Locale.indonesian: "bulan-ini",
        Locale.danish: "denne-måned",
        Locale.dutch: "deze-maand",
        Locale.finnish: "tämä-kuukausi",
        Locale.french: "ce-mois",
        Locale.german: "diesen-monat",
        Locale.greek: "αυτόν-τον-μήνα",
        Locale.hindi: "इस-महीने",
        Locale.hungarian: "ebben-a-hónapban",
        Locale.italian: "questo-mese",
        Locale.japanese: "今月",
        Locale.korean: "이번달",
        Locale.latin_american_spanish: "este-mes",
        Locale.lithuanian: "šį-mėnesį",
        Locale.norwegian: "denne-måneden",
        Locale.polish: "ten-miesiąc",
        Locale.brazil_portuguese: "este-mês",
        Locale.romanian: "luna-aceasta",
        Locale.russian: "этот-месяц",
        Locale.spain_spanish: "este-mes",
        Locale.swedish: "denna-månad",
        Locale.thai: "เดือนนี้",
        Locale.turkish: "bu-ay",
        Locale.ukrainian: "цього-місяця",
        Locale.vietnamese: "tháng-này",
    },

    "올해": {
        Locale.american_english: "this-year",
        Locale.british_english: "this-year",
        Locale.bulgarian: "тази-година",
        Locale.chinese: "今年",
        Locale.taiwan_chinese: "今年",
        Locale.croatian: "ove-godine",
        Locale.czech: "tento-rok",
        Locale.indonesian: "tahun-ini",
        Locale.danish: "dette-år",
        Locale.dutch: "dit-jaar",
        Locale.finnish: "tänä-vuonna",
        Locale.french: "cette-année",
        Locale.german: "dieses-jahr",
        Locale.greek: "φέτος",
        Locale.hindi: "इस-वर्ष",
        Locale.hungarian: "idén",
        Locale.italian: "quest-anno",
        Locale.japanese: "今年",
        Locale.korean: "올해",
        Locale.latin_american_spanish: "este-año",
        Locale.lithuanian: "šiemet",
        Locale.norwegian: "dette-året",
        Locale.polish: "ten-rok",
        Locale.brazil_portuguese: "este-ano",
        Locale.romanian: "anul-acesta",
        Locale.russian: "этот-год",
        Locale.spain_spanish: "este-año",
        Locale.swedish: "detta-år",
        Locale.thai: "ปีนี้",
        Locale.turkish: "bu-yıl",
        Locale.ukrainian: "цього-року",
        Locale.vietnamese: "năm-nay",
    },

    "직접입력": {
        Locale.american_english: "custom",
        Locale.british_english: "custom",
        Locale.bulgarian: "по-избор",
        Locale.chinese: "自定义",
        Locale.taiwan_chinese: "自訂",
        Locale.croatian: "prilagođeno",
        Locale.czech: "vlastní",
        Locale.indonesian: "khusus",
        Locale.danish: "brugerdefineret",
        Locale.dutch: "aangepast",
        Locale.finnish: "mukautettu",
        Locale.french: "personnalisé",
        Locale.german: "benutzerdefiniert",
        Locale.greek: "προσαρμοσμένο",
        Locale.hindi: "कस्टम",
        Locale.hungarian: "egyéni",
        Locale.italian: "personalizzato",
        Locale.japanese: "カスタム",
        Locale.korean: "직접입력",
        Locale.latin_american_spanish: "personalizado",
        Locale.lithuanian: "pasirinktinis",
        Locale.norwegian: "egendefinert",
        Locale.polish: "niestandardowe",
        Locale.brazil_portuguese: "personalizado",
        Locale.romanian: "personalizat",
        Locale.russian: "пользовательский",
        Locale.spain_spanish: "personalizado",
        Locale.swedish: "anpassad",
        Locale.thai: "กำหนดเอง",
        Locale.turkish: "özel",
        Locale.ukrainian: "власний",
        Locale.vietnamese: "tùy-chỉnh",
    },

    # ========================================
    # 기자
    # ========================================

    "기자": {
        Locale.american_english: "reporter",
        Locale.british_english: "reporter",
        Locale.bulgarian: "репортер",
        Locale.chinese: "记者",
        Locale.taiwan_chinese: "記者",
        Locale.croatian: "novinar",
        Locale.czech: "reportér",
        Locale.indonesian: "reporter",
        Locale.danish: "reporter",
        Locale.dutch: "verslaggever",
        Locale.finnish: "toimittaja",
        Locale.french: "reporter",
        Locale.german: "reporter",
        Locale.greek: "ρεπόρτερ",
        Locale.hindi: "रिपोर्टर",
        Locale.hungarian: "riporter",
        Locale.italian: "reporter",
        Locale.japanese: "記者",
        Locale.korean: "기자",
        Locale.latin_american_spanish: "reportero",
        Locale.lithuanian: "žurnalistas",
        Locale.norwegian: "reporter",
        Locale.polish: "reporter",
        Locale.brazil_portuguese: "repórter",
        Locale.romanian: "reporter",
        Locale.russian: "репортер",
        Locale.spain_spanish: "reportero",
        Locale.swedish: "reporter",
        Locale.thai: "นักข่าว",
        Locale.turkish: "muhabir",
        Locale.ukrainian: "репортер",
        Locale.vietnamese: "phóng-viên",
    },

    "파견": {
        Locale.american_english: "dispatch",
        Locale.british_english: "dispatch",
        Locale.bulgarian: "изпрати",
        Locale.chinese: "派遣",
        Locale.taiwan_chinese: "派遣",
        Locale.croatian: "pošalji",
        Locale.czech: "vyslat",
        Locale.indonesian: "kirim",
        Locale.danish: "udsend",
        Locale.dutch: "uitzenden",
        Locale.finnish: "lähetä",
        Locale.french: "déployer",
        Locale.german: "entsenden",
        Locale.greek: "αποστολή",
        Locale.hindi: "भेजें",
        Locale.hungarian: "kiküldés",
        Locale.italian: "invia",
        Locale.japanese: "派遣",
        Locale.korean: "파견",
        Locale.latin_american_spanish: "enviar",
        Locale.lithuanian: "išsiųsti",
        Locale.norwegian: "send",
        Locale.polish: "wyślij",
        Locale.brazil_portuguese: "enviar",
        Locale.romanian: "trimite",
        Locale.russian: "отправить",
        Locale.spain_spanish: "enviar",
        Locale.swedish: "skicka",
        Locale.thai: "ส่ง",
        Locale.turkish: "gönder",
        Locale.ukrainian: "відправити",
        Locale.vietnamese: "phái-cử",
    },

    "철수": {
        Locale.american_english: "recall",
        Locale.british_english: "recall",
        Locale.bulgarian: "отзови",
        Locale.chinese: "撤回",
        Locale.taiwan_chinese: "撤回",
        Locale.croatian: "povuci",
        Locale.czech: "stáhnout",
        Locale.indonesian: "tarik",
        Locale.danish: "tilbagekald",
        Locale.dutch: "terugtrekken",
        Locale.finnish: "vetäytyä",
        Locale.french: "rappeler",
        Locale.german: "zurückrufen",
        Locale.greek: "ανάκληση",
        Locale.hindi: "वापस-बुलाएँ",
        Locale.hungarian: "visszahívás",
        Locale.italian: "ritira",
        Locale.japanese: "撤退",
        Locale.korean: "철수",
        Locale.latin_american_spanish: "retirar",
        Locale.lithuanian: "atšaukti",
        Locale.norwegian: "trekk-tilbake",
        Locale.polish: "wycofaj",
        Locale.brazil_portuguese: "retirar",
        Locale.romanian: "retrage",
        Locale.russian: "отозвать",
        Locale.spain_spanish: "retirar",
        Locale.swedish: "återkalla",
        Locale.thai: "ถอน",
        Locale.turkish: "geri-çek",
        Locale.ukrainian: "відкликати",
        Locale.vietnamese: "rút-về",
    },

    "현황": {
        Locale.american_english: "status",
        Locale.british_english: "status",
        Locale.bulgarian: "статус",
        Locale.chinese: "状态",
        Locale.taiwan_chinese: "狀態",
        Locale.croatian: "status",
        Locale.czech: "stav",
        Locale.indonesian: "status",
        Locale.danish: "status",
        Locale.dutch: "status",
        Locale.finnish: "tila",
        Locale.french: "statut",
        Locale.german: "status",
        Locale.greek: "κατάσταση",
        Locale.hindi: "स्थिति",
        Locale.hungarian: "állapot",
        Locale.italian: "stato",
        Locale.japanese: "状況",
        Locale.korean: "현황",
        Locale.latin_american_spanish: "estado",
        Locale.lithuanian: "būsena",
        Locale.norwegian: "status",
        Locale.polish: "status",
        Locale.brazil_portuguese: "status",
        Locale.romanian: "stare",
        Locale.russian: "статус",
        Locale.spain_spanish: "estado",
        Locale.swedish: "status",
        Locale.thai: "สถานะ",
        Locale.turkish: "durum",
        Locale.ukrainian: "статус",
        Locale.vietnamese: "trạng-thái",
    },
}


class ChronicleTranslator(
    app_commands.Translator,
):

    async def translate(
        self,
        string: app_commands.locale_str,
        locale: Locale,
        context: app_commands.TranslationContext,
    ) -> str | None:

        translations = TRANSLATIONS.get(
            string.message,
        )

        if translations is None:
            return None

        return translations.get(
            locale,
        )